### ISSUE TITLE
Windows wheels don't get uploaded to rackspace

### ISSUE THREAD

**Issue by mpenkov** [MacPython/gensim-wheels#15]
If you look at [this build](https://ci.appveyor.com/project/piskvorky/gensim-wheels/build/job/8kpujlm29c48w1n2), you'll see this at the end:

```
Wheelhouse successfully published at:
http://b153eb958f4da6029aca-3f9dff7fe564350f10153d8c7bfc5ab6.r54.cf2.rackcdn.com
made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Collecting artifacts...
Found artifact 'gensim\dist\gensim-3.8.1-cp27-cp27m-win32.whl' matching 'gensim\dist\*' path
Found artifact 'gensim\dist\gensim-3.8.1.win32-py2.7.exe' matching 'gensim\dist\*' path
Uploading artifacts...
[1/2] gensim\dist\gensim-3.8.1-cp27-cp27m-win32.whl (23,971,739 bytes)...100%
[2/2] gensim\dist\gensim-3.8.1.win32-py2.7.exe (24,158,297 bytes)...100%
Build success
```

So the wheel and windows installer .exe should have been uploaded to [this URL](http://b153eb958f4da6029aca-3f9dff7fe564350f10153d8c7bfc5ab6.r54.cf2.rackcdn.com). Unfortunately, if you go there, you won't see them there.

Only Windows wheels and installers are affected. Other platforms (Linux and MacOS) get uploaded fine.

**Comment by matthew-brett** [comment]
Is it possible you're in the wrong directory for the upload?   I think this is the last upload that worked:

https://ci.appveyor.com/project/piskvorky/gensim-wheels/builds/22028006/job/34ixjjsnfhiekj87

It looks to me as if, for that build, you have a `cd ../gensim/dist` step, but I can't see that step in your latest build...

**Comment by mpenkov** [comment]
@matthew-brett Good catch! I'll look into that.

**Comment by menshikh-iv** [comment]
Сhecked Mattew idea. Looks like that's was a real reason of the issue, see https://github.com/MacPython/gensim-wheels/pull/16

@mpenkov please finalize #16, you know, what to do :)
